<?php require_once __DIR__.'/../app/layout.php';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$name=trim($_POST['full_name']??'');$mobile=preg_replace('/\D/','',$_POST['mobile']??'');$email=filter_var($_POST['email']??'',FILTER_VALIDATE_EMAIL);$password=$_POST['password']??'';
    if(strlen($name)<2||!preg_match('/^\d{10,15}$/',$mobile)||!$email||strlen($password)<8)flash('Enter a valid name, mobile number, email and a password of at least 8 characters.','error');
    else{try{$pdo->prepare('INSERT INTO members (full_name,mobile,email,password_hash) VALUES (?,?,?,?)')->execute([$name,$mobile,$email,password_hash($password,PASSWORD_DEFAULT)]);flash('Thank you for your registration. Your membership request has been submitted for approval.');redirect('/register.php');}catch(PDOException $e){flash('That email address or mobile number is already registered.','error');}}
}
header_html('Membership registration');?>
<style>body:has(.membership-register){background:linear-gradient(90deg,#fff9f0d9,#ffffffd9),url('/assets/membership-background.png') center/cover fixed}.membership-register{max-width:460px;margin:clamp(20px,6vh,70px) auto;padding:32px;background:#fffffff2;border:1px solid #ffffff;border-radius:18px;box-shadow:0 18px 50px #102a5240}.membership-register h1{margin:0;font-size:2.2rem;text-align:center}.membership-register .intro{text-align:center;margin:8px 0 24px;color:#586579}.membership-register form{padding:0;background:transparent;border:0;box-shadow:none}.membership-register label{font-size:.92rem;font-weight:700}.membership-register input{margin-bottom:12px}.membership-register button{width:100%;margin-top:8px}.membership-register .login-link{text-align:center;margin:18px 0 0;font-size:.9rem}</style>
<section class="membership-register"><h1>Join TSSMT</h1><p class="intro">Become part of a community dedicated to preserving Talcher’s freedom-fighter legacy.</p><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><label>Full Name<input name="full_name" required maxlength="150" autocomplete="name"></label><label>Mobile Number<input name="mobile" inputmode="numeric" required autocomplete="tel"></label><label>Email Address<input type="email" name="email" required autocomplete="email"></label><label>Create Password<input type="password" name="password" minlength="8" required autocomplete="new-password"></label><button>Submit membership request</button></form><p class="login-link">Already a member? <a href="/login.php">Sign in</a></p></section><?php footer_html();
